service: api-service

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: eu-west-1
  memorySize: 256
  environment:
    TABLE_NAME: ${self:patients}
  apiGateway:
    shouldStartNameWithService: true
    apiKeys:
      - ${opt:stage}-Api

plugins:
  - serverless-offline

useDotenv: true

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-infections
  tableThroughputs:
    prod: 1
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

functions:
  getPaitient:
    handler: handlers.getPatient
    events:
      - http:
          path: patients
          method: get
  createPatient:
    handler: handlers.createPatient
    events:
      - http:
          path: patients
          method: post
          cors: true

resources:
  - ${file(resources/dynamodb-table.yml)}